// Reads the summary comments a slicer writes into a G-code file. Nothing here touches the network.
const sum = (str) => str.split(",").map(parseFloat).filter(Number.isFinite).reduce((a, b) => a + b, 0);

function duration(str) {
  let sec = 0, found = false;
  for (const [, n, unit] of str.matchAll(/(\d+(?:\.\d+)?)\s*([dhms])/g)) {
    found = true;
    sec += Number(n) * { d: 86400, h: 3600, m: 60, s: 1 }[unit];
  }
  return found ? sec : null;
}

// Returns { slicer, seconds, grams, gramsFrom: "file" | "length" | null, lengthMm }. Missing values are null.
export function parseGcode(text, { density = 1.24, diameter = 1.75 } = {}) {
  const pick = (re) => re.exec(text)?.[1];
  const slicer = pick(/generated by (\w+)/i)
    || (/Cura_SteamEngine/i.test(text) ? "Cura" : /Bambu ?Studio/i.test(text) ? "Bambu Studio" : null);

  let seconds = null;
  const normal = pick(/estimated printing time \(normal mode\)\s*=\s*([^\r\n]+)/i);
  const total = pick(/total estimated time:\s*([0-9dhms .]+)/i);
  const cura = pick(/^;TIME:\s*(\d+)/im);
  if (normal) seconds = duration(normal);
  if (seconds === null && total) seconds = duration(total);
  if (seconds === null && cura) seconds = Number(cura);

  let grams = null, gramsFrom = null, lengthMm = null;
  const g = pick(/total filament (?:used|weight) \[g\]\s*[=:]\s*([ \d.,]+)/i) ?? pick(/filament used \[g\]\s*=\s*([ \d.,]+)/i);
  if (g !== undefined && sum(g) > 0) { grams = sum(g); gramsFrom = "file"; }

  const mm = pick(/filament used \[mm\]\s*=\s*([ \d.,]+)/i) ?? pick(/total filament length \[mm\]\s*[=:]\s*([ \d.,]+)/i);
  if (mm !== undefined) {
    lengthMm = sum(mm) || null;
  } else {
    const line = pick(/^;Filament used:\s*([^\r\n]+)/im); // Cura: metres, e.g. "1.87545m"
    if (line) lengthMm = [...line.matchAll(/([\d.]+)\s*m/g)].reduce((a, x) => a + Number(x[1]) * 1000, 0) || null;
  }
  if (grams === null && lengthMm) {
    grams = (Math.PI * (diameter / 2) ** 2 * lengthMm / 1000) * density; // mm3 to cm3, times g/cm3
    gramsFrom = "length";
  }
  return { slicer, seconds, grams, gramsFrom, lengthMm };
}
